# 1. Preload the files first (Mandatory for the stable version)
preload = ~/.config/hypr/wallpapers/default

# 2. Set the wallpaper
# Format: wallpaper = MONITOR,PATH
wallpaper = ,~/.config/hypr/wallpapers/default
